// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdktmnzetynreahdpjim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpka3RtbnpldHlucmVhaGRwamltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNzkxOTYsImV4cCI6MjA3MTg1NTE5Nn0.LIHb2ksu58zLyHjs3axx-rglGSzbfWZyJuQbf8bpPkg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});